### ISSUE TITLE
Multicolor Feature

### ISSUE THREAD

**Issue by rhuangabrielsantos** [CeamKrier/react-peeps#37]
**First of all I found the lib implementation amazing!**

It would be nice to implement the multicolor functionality of open peeps, I personally find the color version more beautiful for some sites.
I even have the multicolor figma, what do you think of the implementation?

https://www.figma.com/file/7MedgXLQyuAKtB5dFG6mRw/open-peeps?node-id=0%3A1&t=pMBZbcELsDrtoyzF-1

![image](https://user-images.githubusercontent.com/50742592/232169927-49acac4c-7e28-4673-af9e-c40458251fe0.png)

**Comment by CeamKrier** [comment]
I appreciate your kind words about the implementation of the library. However, I'm sorry to say that I currently don't have the free time to work on implementing the multicolor functionality of Open Peeps.

That being said, I encourage you to consider implementing the feature yourself. Open-source projects thrive on contributions from the community, and your input would be greatly appreciated. If you need any help or guidance along the way, I'd be happy to assist in any way I can!
